window.MODULES = window.MODULES || [];
window.MODULES.push({
  icon:'💎', title:'Abstract Algebra', desc:'Groups, rings, fields, cyclic groups, Lagrange theorem, and cryptography.',
  topics:[
    {title:'4.1 Axioms of Group Theory',
     content:`<div class="box box-def"><span class="box-label">Definition: Group</span>
<p>A <b>group</b> (G, ∗) is a set G with operation ∗ satisfying:</p>
<ol>
<li><b>Closure:</b> ∀a,b ∈ G → a∗b ∈ G</li>
<li><b>Associativity:</b> (a∗b)∗c = a∗(b∗c)</li>
<li><b>Identity:</b> ∃e ∈ G such that a∗e = e∗a = a for all a</li>
<li><b>Inverse:</b> ∀a ∈ G, ∃a⁻¹ such that a∗a⁻¹ = a⁻¹∗a = e</li>
</ol>
<p>If also <b>commutative</b> (a∗b = b∗a), it's an <b>Abelian group</b>.</p></div>
<div class="box box-warn"><span class="box-label">⚠️ Exam Tip</span>
<p>To prove something is NOT a group, find ONE axiom that fails. Usually check closure or inverses first — they fail most often.</p></div>`,
     quiz:{q:'Which axiom is NOT required for a group?', opts:['Closure','Commutativity','Associativity','Existence of inverse'], ans:1}
    },

    {title:'4.2 Addition Modulo Groups',
     content:`<div class="box box-def"><span class="box-label">Definition</span>
<p><b>ℤₙ = {0, 1, 2, ..., n-1}</b> under addition mod n forms a group.</p></div>
<div class="box box-ex"><span class="box-label">Example: ℤ₆ = {0,1,2,3,4,5}</span>
<ul>
<li><b>Operation:</b> a +₆ b = (a+b) mod 6</li>
<li><b>Identity:</b> 0</li>
<li><b>Inverse of a:</b> n - a (e.g., inverse of 2 is 4 since 2+4=6≡0)</li>
<li>This is always an <b>Abelian group</b></li>
</ul></div>`,
     quiz:{q:'In ℤ₇, what is the inverse of 3?', opts:['3','4','7','0'], ans:1}
    },

    {title:'4.3 Multiplication Modulo Groups',
     content:`<div class="box box-def"><span class="box-label">Definition</span>
<p><b>U(n)</b> = {a ∈ ℤₙ : gcd(a, n) = 1} under multiplication mod n.</p>
<p>Only elements <b>coprime to n</b> have inverses, so only they can form a group.</p></div>
<div class="box box-ex"><span class="box-label">Example: U(10) = {1, 3, 7, 9}</span>
<table class="truth-table">
<tr><th>×₁₀</th><th>1</th><th>3</th><th>7</th><th>9</th></tr>
<tr><td><b>1</b></td><td>1</td><td>3</td><td>7</td><td>9</td></tr>
<tr><td><b>3</b></td><td>3</td><td>9</td><td>1</td><td>7</td></tr>
<tr><td><b>7</b></td><td>7</td><td>1</td><td>9</td><td>3</td></tr>
<tr><td><b>9</b></td><td>9</td><td>7</td><td>3</td><td>1</td></tr>
</table>
<p>Identity = 1. Inverse of 3 is 7 (since 3×7=21≡1 mod 10). |U(10)| = φ(10) = 4.</p></div>
<div class="box box-tip"><span class="box-label">💡 Euler's Totient</span>
<p>|U(n)| = φ(n) = number of integers from 1 to n coprime to n.<br>
If p is prime: <b>U(p) = {1,2,...,p-1}</b> and φ(p) = p-1.</p></div>`,
     quiz:{q:'Which elements are in U(12)?', opts:['{1,2,3,4,5,6,7,8,9,10,11}','{1,5,7,11}','{1,2,4,8}','{1,3,5,7,9,11}'], ans:1}
    },

    {title:'4.4-4.5 Important Groups & Order',
     content:`<div class="box box-thm"><span class="box-label">Common Groups</span>
<ul>
<li><b>(ℤ, +)</b> — integers under addition. Infinite Abelian group.</li>
<li><b>(ℚ*, ×)</b> — nonzero rationals under multiplication.</li>
<li><b>Dₙ</b> — Dihedral group: symmetries of regular n-gon. |Dₙ| = 2n.</li>
<li><b>Sₙ</b> — Symmetric group: all permutations of n elements. |Sₙ| = n!</li>
<li><b>GL₂(ℝ)</b> — invertible 2×2 matrices. Non-abelian!</li>
</ul></div>
<div class="box box-def"><span class="box-label">Order</span>
<ul>
<li><b>Order of group |G|:</b> number of elements</li>
<li><b>Order of element a:</b> smallest positive n such that aⁿ = e. Written ord(a) or |a|.</li>
<li>If no such n exists, a has <b>infinite order</b></li>
</ul></div>
<div class="box box-ex"><span class="box-label">Example</span>
<p>In ℤ₆ under addition: ord(2) = ? We compute: 2, 2+2=4, 4+2=6≡0. So ord(2) = <b>3</b>.</p>
<p>In U(10): ord(3) = ? We compute: 3¹=3, 3²=9, 3³=27≡7, 3⁴=81≡1. So ord(3) = <b>4</b>.</p></div>`,
     quiz:{q:'In ℤ₈ (addition mod 8), what is the order of element 6?', opts:['2','3','4','8'], ans:2}
    },

    {title:'4.6 Cyclic Groups',
     content:`<div class="box box-def"><span class="box-label">Definition</span>
<p>A group G is <b>cyclic</b> if ∃g ∈ G such that every element = gⁿ for some integer n. We say g <b>generates</b> G: G = ⟨g⟩.</p></div>
<div class="box box-thm"><span class="box-label">Key Facts</span>
<ul>
<li>Every cyclic group is <b>Abelian</b></li>
<li>ℤₙ is cyclic (generated by 1)</li>
<li><b>Generators of ℤₙ:</b> those a where gcd(a,n) = 1</li>
<li>Number of generators = φ(n)</li>
<li>Subgroups of cyclic groups are cyclic</li>
<li>For each divisor d of n, there's exactly ONE subgroup of order d in ℤₙ</li>
</ul></div>
<div class="box box-ex"><span class="box-label">Example</span>
<p>ℤ₁₂: generators are elements coprime to 12: {1,5,7,11}. φ(12) = 4 generators.</p>
<p>⟨4⟩ = {0, 4, 8} — subgroup of order 3 (since 12/gcd(4,12) = 12/4 = 3).</p></div>`,
     quiz:{q:'How many generators does ℤ₈ have?', opts:['2','4','6','8'], ans:1}
    },

    {title:"4.7 Lagrange's Theorem",
     content:`<div class="box box-thm"><span class="box-label">Lagrange's Theorem</span>
<p>If H is a subgroup of finite group G, then <b>|H| divides |G|</b>.</p></div>
<div class="box box-thm"><span class="box-label">Corollaries (SUPER Important!)</span>
<ol>
<li><b>Order of element divides order of group:</b> ord(a) divides |G|</li>
<li><b>Groups of prime order are cyclic:</b> If |G| = p (prime), G ≅ ℤₚ</li>
<li><b>Fermat's Little Theorem:</b> If p prime and gcd(a,p)=1, then aᵖ⁻¹ ≡ 1 (mod p)</li>
<li><b>Euler's Theorem:</b> If gcd(a,n)=1, then aᶠ⁽ⁿ⁾ ≡ 1 (mod n)</li>
</ol></div>
<div class="box box-ex"><span class="box-label">Example</span>
<p><b>Q:</b> G has order 33. If x ≠ e and x¹¹ ≠ e, what is ord(x)?</p>
<div class="spoiler"><button class="spoiler-toggle">👁 Show Solution</button><div class="spoiler-content">
<div class="steps">
<div class="step">By Lagrange, ord(x) divides 33. Divisors of 33: 1, 3, 11, 33.</div>
<div class="step">x ≠ e → ord(x) ≠ 1</div>
<div class="step">x¹¹ ≠ e → ord(x) does not divide 11. So ord(x) ≠ 1 and ≠ 11.</div>
<div class="step">Remaining: 3 or 33. But if ord(x) = 3, then x³ = e, so x¹¹ = x²(x³)³ = x² ≠ e (need to check). Actually if ord=3, x¹¹ = x^(3·3+2) = x² ≠ e ✓ (consistent).</div>
<div class="step">So ord(x) could be <b>3 or 33</b>.</div>
</div></div></div></div>`,
     quiz:{q:'If |G| = 30, can an element have order 8?', opts:['Yes','No, because 8 does not divide 30','Only if G is Abelian','Only if G is cyclic'], ans:1}
    },

    {title:'4.8-4.10 Rings and Fields',
     content:`<div class="box box-def"><span class="box-label">Ring (R, +, ·)</span>
<ol>
<li>(R, +) is an <b>Abelian group</b></li>
<li>Multiplication is <b>associative</b></li>
<li><b>Distributive:</b> a(b+c) = ab+ac and (a+b)c = ac+bc</li>
</ol>
<p>If multiplication is commutative → <b>commutative ring</b>. If ∃ multiplicative identity 1 → <b>ring with unity</b>.</p></div>

<div class="box box-def"><span class="box-label">Field</span>
<p>A field is a commutative ring with unity where <b>every nonzero element has a multiplicative inverse</b>.</p>
<p><b>Examples:</b> ℚ, ℝ, ℂ, ℤₚ (p prime)</p>
<p><b>Non-examples:</b> ℤ (no multiplicative inverses for most elements), ℤ₆ (2×3=0, zero divisors)</p></div>

<div class="box box-warn"><span class="box-label">⚠️ Key Difference</span>
<p>ℤₙ is a field ⟺ n is <b>prime</b>. If n is composite, there are zero divisors (ab ≡ 0 but a,b ≠ 0).</p></div>`,
     quiz:{q:'Which is a field?', opts:['ℤ₆','ℤ₉','ℤ₇','ℤ₁₅'], ans:2}
    },

    {title:'4.9 Polynomial Rings',
     content:`<div class="box box-def"><span class="box-label">Definition</span>
<p><b>R[x]</b> = set of all polynomials with coefficients from ring R.</p>
<p>Operations: add/multiply polynomials, reducing coefficients mod n if in ℤₙ[x].</p></div>
<div class="box box-ex"><span class="box-label">Example (from your assignments)</span>
<p><b>Compute (3x² + 2x - 4) + (4x² + 2) in ℤ₅[x]:</b></p>
<div class="spoiler"><button class="spoiler-toggle">👁 Show Solution</button><div class="spoiler-content">
<div class="steps">
<div class="step">Add coefficients: (3+4)x² + 2x + (-4+2) = 7x² + 2x - 2</div>
<div class="step">Reduce mod 5: 7≡2, 2≡2, -2≡3</div>
<div class="step"><b>Answer: 2x² + 2x + 3 in ℤ₅[x]</b></div>
</div></div></div></div>
<div class="box box-ex"><span class="box-label">Example: Multiplication</span>
<p><b>Compute (3x² + 2x - 4)·(4x² + 2) in ℤ₅[x]:</b></p>
<div class="spoiler"><button class="spoiler-toggle">👁 Show Solution</button><div class="spoiler-content">
<div class="steps">
<div class="step">12x⁴ + 6x² + 8x³ + 4x - 16x² - 8</div>
<div class="step">= 12x⁴ + 8x³ + (6-16)x² + 4x - 8</div>
<div class="step">= 12x⁴ + 8x³ - 10x² + 4x - 8</div>
<div class="step">Mod 5: 2x⁴ + 3x³ + 0x² + 4x + 2</div>
<div class="step"><b>Answer: 2x⁴ + 3x³ + 4x + 2</b></div>
</div></div></div></div>`,
     quiz:{q:'In ℤ₃[x], what is 5x² + 4x + 7?', opts:['2x² + x + 1','5x² + 4x + 7','2x² + 4x + 1','0'], ans:0}
    },

    {title:'4.11-4.12 Primitive Elements & Cryptography',
     content:`<div class="box box-def"><span class="box-label">Primitive Element</span>
<p>In ℤₚ* (p prime), a <b>primitive element (generator)</b> is an element g whose powers give ALL nonzero elements: {g¹, g², ..., gᵖ⁻¹} = {1, 2, ..., p-1}.</p></div>

<div class="box box-thm"><span class="box-label">Discrete Logarithm Problem (DLP)</span>
<p>Given g, p, and h = gˣ mod p, finding x is computationally <b>very hard</b> for large p. This is the foundation of many crypto systems.</p></div>

<div class="box box-thm"><span class="box-label">Diffie-Hellman Key Exchange</span>
<div class="steps">
<div class="step">Alice and Bob agree on public prime p and generator g</div>
<div class="step">Alice picks secret a, sends A = gᵃ mod p</div>
<div class="step">Bob picks secret b, sends B = gᵇ mod p</div>
<div class="step">Alice computes: Bᵃ = (gᵇ)ᵃ = gᵃᵇ mod p</div>
<div class="step">Bob computes: Aᵇ = (gᵃ)ᵇ = gᵃᵇ mod p</div>
<div class="step"><b>Shared secret = gᵃᵇ mod p</b> (Eve only sees g, p, A, B — can't find gᵃᵇ!)</div>
</div></div>

<div class="box box-ex"><span class="box-label">Numerical Example</span>
<p>p=23, g=5, Alice a=6, Bob b=15</p>
<div class="spoiler"><button class="spoiler-toggle">👁 Show Solution</button><div class="spoiler-content">
<div class="steps">
<div class="step">A = 5⁶ mod 23 = 15625 mod 23 = 8</div>
<div class="step">B = 5¹⁵ mod 23 = ... = 19</div>
<div class="step">Alice: 19⁶ mod 23 = 2</div>
<div class="step">Bob: 8¹⁵ mod 23 = 2</div>
<div class="step"><b>Shared key = 2</b></div>
</div></div></div></div>`,
     quiz:{q:'In Diffie-Hellman, what does an eavesdropper see?', opts:['a, b, and gᵃᵇ','g, p, gᵃ mod p, gᵇ mod p','The shared secret','Nothing'], ans:1}
    }
  ]
});
